server:
  port: 8080
output:
  file: "/home/level-128/personBlogFor128/server"
upload:
  filePath: "/home/level-128/personBlogFor128/imgs"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
